image: alpine:latest

pages:
  stage: deploy
  script:
  - cat public/manifest.json | sed 's/otp\.rencloud\.xyz/rensatsu\.gitlab\.io\/otp\-generator/' > public/manifest.json
  artifacts:
    paths:
    - public
  only:
  - master